### ISSUE TITLE
tidyfast::dt_case_when() handles NA conditions differently from dplyr::case_when()

### ISSUE THREAD

**Issue by mdtrinh** [TysonStanley/tidyfast#46]
When one of the conditions returns NA e.g. when the vector contains NA, tidyfast::dt_case_when() returns NA immediately regardless of whether there is an "else" (TRUE ~ ...) condition, whereas dplyr::case_when() skips it and evaluates the "else" condition. This causes the two functions to produce different outputs.

```{r}
## Eg 1
x <- c(1,2,3,4,5,NA)
# returns NA
dt_case_when(x == 1 ~ "a",
             x < 4 ~ "b",
             TRUE ~ "c")
# does not return NA
case_when(x == 1 ~ "a",
          x < 4 ~ "b",
          TRUE ~ "c")

## Eg 2: minimal case
# returns NA
dt_case_when(NA ~ 1, TRUE ~ 2)

# does not return NA
case_when(NA ~ 1, TRUE ~ 2)
```

**Comment by TysonStanley** [comment]
Yes, I've noticed that behavior in the past. I will have a fix soon.
