### ISSUE TITLE
Error in isFALSE(is.data.table(dt_)) : could not find function "isFALSE"

### ISSUE THREAD

**Issue by beritlin** [TysonStanley/tidyfast#49]
Hello, I would like to use tidyfast for separate my data table faster so I installed it and tried to run the example you provided.  However, the error was pop out and Im not sure how to solve this problem. 
my data.table is 1.13.0, is it because it is too old?

```
library(data.table)
library(tidyfast)
dt_separate(data.table(col = "A.B.C"), col, into = c("A", "B"))

Error in isFALSE(is.data.table(dt_)) : could not find function "isFALSE"
```

What could be the problem and any tips to resolve this? Thank you so much!

**Comment by beritlin** [comment]
ok I found out it's data.table problem. my data.table is 0.1.13 but it required 0.1.14 for tidyfast!

**Comment by TysonStanley** [comment]
Oh, that is good to know. I believe the `isFALSE()` function is available in a newer `R` version but I believe `data.table` offers it internally as well.
