### ISSUE TITLE
is_formula is problematic

### ISSUE THREAD

**Issue by moodymudskipper** [TysonStanley/tidyfast#5]
You defined it as : 

```
is_formula <-
function(x){
  class(x) == "formula"
}
```

But class isn't necessarily a scalar, I think you should go for one of those (the first one is the most commonly used, the 3rd and 4th are more rigorous, not sure about performance! )  : 

```
is_formula <- function(x) inherits(x, "formula")
is_formula <- function(x) identical(class(x), "formula")
is_formula <- function(x) is.call(x) && x[[1]] == quote(`~`)
is_formula <- function(x) identical(class(x), "formula") && is.call(x) && x[[1]] == quote(`~`)
```

see https://stackoverflow.com/questions/36361158/how-to-test-if-an-object-is-a-formula-in-base-r/58788220#58788220

**Comment by TysonStanley** [comment]
Clearly I didn't give this proper thought. Thanks for the heads up. Will definitely use:

```
is_formula <- function(x) is.call(x) && x[[1]] == quote(`~`)
```

As it seems most immune to strange circumstances.
