### ISSUE TITLE
Outadate readme regarding dt_separate?

### ISSUE THREAD

**Issue by eliocamp** [TysonStanley/tidyfast#50]
The readme currently states that

> Testing with a 4 MB data set with one variable that has columns of “A.B” repeatedly, shows that dt_separate() is fast but less memory efficient than tidyr::separate().

But the benchmark shows:
> ```
> #> # A tibble: 3 × 3
> #>   expression            median mem_alloc
> #>   <chr>               <bch:tm> <bch:byt>
> #> 1 separate               4.98s    3.89GB
> #> 2 dt_separate             73ms   22.92MB
> #> 3 dt_separate-mutable  65.91ms   19.09MB
> ```

Which, if I'm reading correctly, makes dt_separate orders of magnitude more memory efficient than tidyr::separate!

**Comment by TysonStanley** [comment]
Good catch! That was definitely part of an update that went unnoticed in the README. Thanks for the issue.
