### ISSUE TITLE
Add dt_pivot_longer() and dt_pivot_wider()

### ISSUE THREAD

**Issue by markfairbanks** [TysonStanley/tidyfast#6]
Not sure if you're interested in adding these to your package, but I made these for mine. I made the package to help some coworkers with the transition from `tidyverse` to `data.table`.

A couple things to note:
- They don't have full functionality yet but cover the core features of `pivot_wider()` & `pivot_longer()`
- I currently use `rlang` & `stringr` in my package, but these naturally are easily changeable to base R. I noticed in `tidyfast` you are relying on only `data.table` & `Rcpp` 
- I use a helper function called `characterize()` to convert a vector of bare column names to a character vector, so I'll include the link to that as well.

[pivot_wider](https://github.com/mtfairbanks/gdt/blob/master/R/pivot_wider.R)
[pivot_longer](https://github.com/mtfairbanks/gdt/blob/master/R/pivot_longer.R)
[characterize](https://github.com/mtfairbanks/gdt/blob/master/R/helpers.R)

I'm new to package development so I'm sure there are some ways to improve them. Feel free to use them or not use them, but I figured I would send them over either way

**Comment by markfairbanks** [comment]
Note - I just made an update so that "unselecting" columns works whether in a vector or not. That way this code works:

```r
example_dt <- data.table(x = c(1,2,3), y = c(4,5,6), z = c("a", "a", "b"))

example_dt %>%
  dt_pivot_longer(cols = -z)
```

**Comment by datalorax** [comment]
Hi @mtfairbanks 👋

If this code could be easily implemented into {tidyfast} perhaps you could package it as a PR? That would allow @TysonStanley to easily merge it in and make sure it doesn't break any existing code. I'm guessing you were probably just checking to see if there's interest, but that could also be done through the convo of the PR. 

Unless you have a different preference, @TysonStanley?

**Comment by TysonStanley** [comment]
Yes, thanks @datalorax. @mtfairbanks if you could make a pull request, that would really help integrate these functions. 

I like what you've done. Thanks for suggesting we integrate these functions. The `dt_pivot_*()` functions look great and definitely fit the goals of `tidyfast`. If we can keep it to just the two dependencies of `data.table` and `Rcpp`, that would be ideal, and from what I can see, it shouldn't be too much of an adjustment. You can either send the PR as is and I can make the changes or you can before you make the PR. Whichever works best for you.

I also can see you've used some of the functions from `tidyfast` in your package. If you don't mind citing `tidyfast` in your package (even just in the README) that would be great.

**Comment by TysonStanley** [comment]
Also, if you haven’t done a PR before, you can fork the `tidyfast` repo and then follow [these instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork). Feel free to reach out if you run into issues.

**Comment by markfairbanks** [comment]
@TysonStanley Is there a recommended way to cite packages? Or do I just add "the following functions are from the tidyfast package" with a link to the GitHub page?

Sorry if it was bad form to use your functions. Still pretty new to all this.

**Comment by TysonStanley** [comment]
@mtfairbanks no problem, I totally understand. As a general rule, it is always good to give credit for things like that. For now, it would probably be best to say something like: "Several functions within this package are directly from the [`tidyfast` package](https://tysonbarrett.com/tidyfast/)" in the README and in the DESCRIPTION you can add `tidyfast` as a Suggest.
